### ISSUE TITLE
Create a tutorial with a very basic example

### ISSUE THREAD

**Issue by jfunez** [ArthurFortes/CaseRecommender#22]
I think it may help to anyone who wants to apply or tests CR with a very simple example, or maybe add links to learn basics concepts.

**Comment by arthurfortes** [comment]
Hi, @jfunez !

We have our [Wiki](https://github.com/caserec/CaseRecommender/wiki) and a [folder](https://github.com/caserec/CaseRecommender/tree/master/examples) with some examples of user. 

we are working to improve the usage description of our framework and we welcome all suggestions.

We will take into account your comment and we will try to leave the points raised more clearly.

Thank you!

**Comment by HarshdeepGupta** [comment]
I second @jfunez , there is definitely a need of better documentation!

**Comment by linh47** [comment]
List the paper cites may be helpful.Sometimes we want to know which algorithm is newer.

**Comment by arthurfortes** [comment]
@linh47 In the header of each implemented algorithm, I referenced the authors and the article/ paper, in which I relied to implement the code.
