### ISSUE TITLE
why the performance of algorithm paco,BprMF,groupBased-Bpr are low than the CF and CB?

### ISSUE THREAD

**Issue by 814734522** [ArthurFortes/CaseRecommender#26]
I used the movie-lens' datasets ml-100k to run the code under the rating_prediction ,found that the output of paco,BprMf and group-base Bpr was very bad.i had to read the literatrue of them,and now i need to learn how to setting parameters of these algorithm.so could you give me some suggest to slove this proble?(I even normalized the dataset ,but didn't work )

**Comment by arthurfortes** [comment]
Hello there, 

PaCo, BprMF and group-based Bpr are item_recommendation (as known as ranking or top-N recommendations) based. They predict scores and not ratings. Your problem may be this one. For rating prediction, you could use this algorithms: 

- Matrix Factorization (with and without baseline)
- SVD
- SVD++
- ItemKNN
- Item Attribute KNN
- UserKNN
- User Attribute KNN
- Item NSVD1 (with and without Batch)
- User NSVD1 (with and without Batch)
- Most Popular
- Random
- gSVD++
- Item-MSMF
- (E) CoRec

**Comment by 814734522** [comment]
sorry，i mistook 'Item_recommendation' to 'raing_prediction' .The PaCo BprMF and group-based Bpr's performance were very lower than ItemKNN UserKnn ,even i had to regular my dataset.so what happend to this code?There is something wrong with the parameters in the code？or other problem？ thanks author.

**Comment by arthurfortes** [comment]
Perhaps your data behave better in a neighborhood scenario, having a poor performace in matrix-factorization algorithms. Or you're performing MF-based algorithms with bad parameters. I suggest you try to change the params: factors, learn_rate, epochs, reg_u, reg_i, reg_j, reg_bias. Try to keep random_seed locked to make a fair comparison in your experiments. Regards.
