### ISSUE TITLE
Treat evaluation codes for "nan's" and "inf's"

### ISSUE THREAD

**Issue by arthurfortes** [ArthurFortes/CaseRecommender#3]

**Comment by roopalv54** [comment]
Hi, can you provide some description to this bug.

**Comment by arthurfortes** [comment]
The evaluation functions receive feedback triples or dictionaries containing user, item and scores (or ratings). In some cases, these scores are inf's or nan's, which is not handled by these functions, and the return of these functions are inf or nan too.

**Comment by arthurfortes** [comment]
Version 1.0 solve this problem
