### ISSUE TITLE
A mistake in ecorec.py

### ISSUE THREAD

**Issue by 814734522** [ArthurFortes/CaseRecommender#31]
arthur,i had readed the paper about the corec.py,And had found the code is differnt with the paper.the items which each users hasn't viewed wasn't selected randomly. the code was in ecorec.py line 135,it just shuffle the unlable_set,not to select items randomly. And i had to run the ecorec.py the result was bad .Is there something I haven't done batter？(for exmple,data normalize or other?)

**Comment by 814734522** [comment]
> arthur,i had readed the paper about the corec.py,And had found the code is differnt with the paper.the items which each users hasn't viewed wasn't selected randomly. the code was in ecorec.py line 135,it just shuffle the unlable_set,not to select items randomly. And i had to run the ecorec.py,but the result was bad,Is there something I haven't done batter？(for exmple,data normalize or other?)

**Comment by 814734522** [comment]
> > arthur,i had readed the paper about the corec.py,And had found the code is differnt with the paper.the items which each users hasn't viewed wasn't selected randomly. the code was in ecorec.py line 135,it just shuffle the unlable_set,not to select items randomly. And i had to run the ecorec.py,but the result was bad,Is there something I haven't done batter？(for exmple,data normalize or other?)

**Comment by 814734522** [comment]
> arthur,i had readed the paper about the corec.py,And had found the code is differnt with the paper.the items which each users hasn't viewed wasn't selected randomly. the code was in ecorec.py line 135,it just shuffle the unlable_set,not to selet items randomly. And i had to run the ecorec.py the result was bad for your paper's result,Is there something I haven't done batter？(for exmple,data normalize or other?)

**Comment by arthurfortes** [comment]
The actual implementation of the repository is not the same as the article (randomness of data, confidence measures and some other details). As soon as possible, I will upload a new version of the framework with these and other changes. The pip version is also out of date, in which CoRec does not even work yet.

**Comment by 814734522** [comment]
Thanks for you reply,Could you tell me some of the details?(measures of trust and randomness of data)because i need to complete this work,but i'm not done yet.So tell me how you think about it？（measures of trust and randomness of data）Thanks :).




------------------ 原始邮件 ------------------
发件人: "Arthur Fortes"<notifications@github.com>;
发送时间: 2019年4月21日(星期天) 晚上9:46
收件人: "caserec/CaseRecommender"<CaseRecommender@noreply.github.com>;
抄送: "就一个字"<814734522@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [caserec/CaseRecommender] A mistake in ecorec.py (#31)




The actual implementation of the repository is not the same as the article (randomness of data, measures of trust and some other details). As soon as possible, I will upload a new version of the framework with these and other changes. The pip version is also out of date, in which CoRec does not even work yet.
