### ISSUE TITLE
Evaluation of CoRec

### ISSUE THREAD

**Issue by liv1n9** [ArthurFortes/CaseRecommender#33]
Hi. I'm studying your paper. In Evaluation chapter, table 1, the paper compared RMSE of UserKNN and ItemKNN when applying on original training set and enriched training set. My question is, the unlabeled set taking from original training set for testing is different from the unlabeled set of enriched one. So does it affect the reliability of evaluation? I think the evaluation is reliable if the test sets in all cases are the same. Correct me if i'm wrong.

**Comment by arthurfortes** [comment]
Not really. You use a random uncollected data set to enrich your original data matrix, whether the samples are in your test suite or not. In the end, its test suite serves to validate how much these enriched matrices work better than those used in traditional approaches.
