### ISSUE TITLE
Evaluation of binary NMF

### ISSUE THREAD

**Issue by danisben** [ArthurFortes/CaseRecommender#36]
Hi, Does CaseRecommender support the evaluation of binary non-negative matrix factorization? (All feedback are 0 or 1) 
I've tried to do that but the MAP/NDCG/PREC/RECALL was always zero. It doesn't seem to work. 
If I change the feedback to 0~5 on the same dataset, the evaluation metric works well.

**Comment by philippschw** [comment]
Hi @danisben and others, how did you solve the issue eventually? Did you implement your own solution or used another library? I am facing the same issue. I am building a recommendation engine, where I have a list of things that are encoded binary.
