### ISSUE TITLE
Upgrade pandas indexing functions

### ISSUE THREAD

**Issue by geriskenderi** [ArthurFortes/CaseRecommender#39]
Hello,

Your library seems quite interesting, but when I was trying to use it I saw that it makes use of the pandas .ix function. This attribute has been removed in pandas > 1.0.0 (basically the new 2020 version). Since that is the case, you should fix the original code and use loc or iloc to index, otherwise we can't use this library without downgrading pandas.

**Comment by arthurfortes** [comment]
Problem fixed on version 1.1.1
