### ISSUE TITLE
Item recommendation doesn't accept alternative space types (sep) for test-file

### ISSUE THREAD

**Issue by tscheidt** [ArthurFortes/CaseRecommender#42]
This problem is caused by the line 86 in caserec/recommenders/item_recommendation/base_item_recommendation.py, can easily be fixed by altering line to self.test_set = ReadFile(self.test_file, sep=self.sep).read()

**Comment by arthurfortes** [comment]
Solved with [pull request #41](https://github.com/caserec/CaseRecommender/pull/41).
