### ISSUE TITLE
For neighborhood recommenders (ItemKNN and UserKNN) change the similarity calculation

### ISSUE THREAD

**Issue by arthurfortes** [ArthurFortes/CaseRecommender#5]
For both approaches (rating prediction and item recommendation) change the value 1 for the maximum value in the distance matrix. 

|Bug info: For measures that don't have the range (0-1) the values after transformation will be wrong.

**Comment by mayukh18** [comment]
@ArthurFortes I am taking this up.

**Comment by arthurfortes** [comment]
You can use something like: 

`self.su_matrix = self.su_matrix.max() - self.su_matrix`

**Comment by mayukh18** [comment]
Considering this is `similarity`, I think it will better to keep it in 0-1 range, thus divide the result by max like `self.su_matrix = (self.su_matrix.max() - self.su_matrix)/self.su_matrix.max()`. What's your take on this?

**Comment by arthurfortes** [comment]
It is an interesting and valid observation. If implemented, leave a comment in the code to make users aware. =)

**Comment by arthurfortes** [comment]
Thx for the contribution. =)

**Comment by arthurfortes** [comment]
Now, only item recommendation is missing =)

**Comment by mayukh18** [comment]
Oh I thought it was only in rating prediction like you said. I'll send in another PR.
